# Generated by Django 3.2.12 on 2022-08-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50, verbose_name='Film adı')),
                ('resim', models.FileField(null=True, upload_to='filmler/', verbose_name='Filmler')),
            ],
        ),
    ]
